import { StyleSheet } from 'react-native';
import {
  colors,
  fonts,
  fontSize,
  spacing,
  borderRadius,
} from '@/constants/theme';

const TEXT_SHADOW = {
  textShadowColor: 'rgba(0, 0, 0, 0.3)',
  textShadowOffset: { width: 0, height: 2 },
  textShadowRadius: 4,
} as const;

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[12],
    paddingBottom: spacing[10],
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[6],
  },
  headerSpacer: {
    width: 44,
  },
  statusCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: borderRadius.xl,
    paddingVertical: spacing[6],
    alignItems: 'center',
    marginBottom: spacing[6],
    gap: spacing[2],
  },
  statusCardFinished: {
    backgroundColor: 'rgba(21, 128, 61, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(21, 128, 61, 0.4)',
  },
  statusLabel: {
    fontFamily: fonts.semiBold,
    fontSize: fontSize.base,
    lineHeight: 20,
    color: colors.textInverse,
    textAlign: 'center',
    ...TEXT_SHADOW,
  },
  roundText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.sm,
    lineHeight: 18,
    color: 'rgba(255, 255, 255, 0.7)',
    letterSpacing: 1,
  },
  resultCard: {
    backgroundColor: colors.ctaSolid,
    borderRadius: borderRadius.xl,
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[5],
    marginBottom: spacing[6],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[4],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  resultAvatar: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  resultAvatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xl,
    color: colors.textInverse,
  },
  resultInfo: {
    flex: 1,
  },
  resultName: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xl,
    lineHeight: 26,
    color: colors.textInverse,
    ...TEXT_SHADOW,
  },
  resultLabel: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xs,
    lineHeight: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    letterSpacing: 1,
    marginTop: spacing[1],
  },
  errorBanner: {
    backgroundColor: colors.error,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  errorText: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    lineHeight: 18,
    color: colors.textInverse,
    flex: 1,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSize.md,
    lineHeight: 22,
    color: colors.textInverse,
    letterSpacing: 0.5,
    marginBottom: spacing[3],
    ...TEXT_SHADOW,
  },
  loadingIndicator: {
    marginTop: spacing[8],
  },
  playersList: {
    gap: spacing[3],
    marginBottom: spacing[8],
  },
  playerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: borderRadius.xl,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    gap: spacing[3],
  },
  playerRowPayer: {
    backgroundColor: 'rgba(253, 94, 129, 0.25)',
    borderWidth: 1,
    borderColor: colors.ctaSolid,
  },
  playerAvatar: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    backgroundColor: colors.ctaSolid,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  playerAvatarPayer: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  playerAvatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.md,
    color: colors.textInverse,
  },
  playerName: {
    flex: 1,
    fontFamily: fonts.semiBold,
    fontSize: fontSize.base,
    lineHeight: 20,
    color: colors.textInverse,
    ...TEXT_SHADOW,
  },
  paysBadge: {
    backgroundColor: colors.ctaSolid,
    borderRadius: borderRadius.full,
    paddingVertical: spacing[1],
    paddingHorizontal: spacing[3],
  },
  paysBadgeText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xs,
    lineHeight: 14,
    color: colors.textInverse,
    letterSpacing: 0.5,
  },
  actions: {
    gap: spacing[3],
  },
});

export default styles;
