import { StyleSheet } from 'react-native';
import {
  colors,
  fonts,
  fontSize,
  spacing,
  borderRadius,
} from '@/constants/theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[12],
    paddingBottom: spacing[10],
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[6],
  },
  greetingWrap: {
    flex: 1,
  },
  greeting: {
    fontFamily: fonts.bold,
    fontSize: fontSize['3xl'],
    lineHeight: 36,
    color: colors.textInverse,
    letterSpacing: -0.25,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subGreeting: {
    fontFamily: fonts.semiBold,
    fontSize: fontSize.base,
    lineHeight: 22,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: spacing[1],
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  avatarButton: {
    padding: spacing[1],
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    backgroundColor: colors.ctaSolid,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    overflow: 'hidden',
  },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
  },
  avatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.lg,
    lineHeight: 25,
    color: colors.textInverse,
  },
  promoBanner: {
    backgroundColor: colors.ctaSolid,
    borderRadius: borderRadius.xl,
    padding: spacing[5],
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[6],
    overflow: 'hidden',
    minHeight: 140,
  },
  promoContent: {
    flex: 1,
    paddingRight: spacing[3],
  },
  promoTag: {
    fontFamily: fonts.semiBold,
    fontSize: fontSize.xs,
    lineHeight: 14,
    color: colors.textInverse,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: spacing[1],
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  promoHeading: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xl,
    lineHeight: 28,
    color: colors.textInverse,
    letterSpacing: 0,
    marginBottom: spacing[3],
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  promoButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.textInverse,
    borderRadius: borderRadius.full,
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[5],
  },
  promoButtonText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.sm,
    lineHeight: 16,
    color: colors.ctaSolid,
    letterSpacing: 0.5,
  },
  promoImage: {
    width: 110,
    height: 110,
    borderRadius: borderRadius.lg,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[3],
    marginBottom: spacing[6],
  },
  actionCard: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: colors.ctaSolid,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing[5],
    paddingHorizontal: spacing[4],
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  actionCardPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },
  actionIconWrap: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
  },
  actionIconShadow: {
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  actionLabel: {
    fontFamily: fonts.bold,
    fontSize: fontSize.md,
    lineHeight: 22,
    color: colors.textInverse,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  ctaSection: {
    gap: 0,
  },
});

export default styles;
