import { StyleSheet } from 'react-native';
import {
  colors,
  fonts,
  fontSize,
  spacing,
  borderRadius,
} from '@/constants/theme';

const TEXT_SHADOW = {
  textShadowColor: 'rgba(0, 0, 0, 0.3)',
  textShadowOffset: { width: 0, height: 2 },
  textShadowRadius: 4,
} as const;

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing[5],
    paddingTop: spacing[12],
    paddingBottom: spacing[10],
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[8],
  },
  headerTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSize['2xl'],
    color: colors.textInverse,
    letterSpacing: 1,
    ...TEXT_SHADOW,
  },
  avatarCircle: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    backgroundColor: colors.ctaSolid,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  avatarText: {
    fontFamily: fonts.bold,
    fontSize: fontSize.xl,
    color: colors.textInverse,
    ...TEXT_SHADOW,
  },
  profileImageSection: {
    alignSelf: 'center',
    width: 110,
    height: 110,
    marginBottom: spacing[6],
  },
  profileImageContainer: {
    width: 100,
    height: 100,
    borderRadius: borderRadius.full,
    overflow: 'hidden',
    backgroundColor: colors.ctaSolid,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  profileImage: {
    width: 100,
    height: 100,
  },
  profileInitials: {
    fontFamily: fonts.bold,
    fontSize: fontSize['3xl'],
    color: colors.textInverse,
    ...TEXT_SHADOW,
  },
  cameraIconOverlay: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 36,
    height: 36,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  inputContainer: {
    marginBottom: spacing[3],
  },
  inputLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: colors.textInverse,
    marginBottom: spacing[2],
    marginLeft: spacing[2],
    ...TEXT_SHADOW,
  },
  inputPill: {
    backgroundColor: '#FFFFFF',
    borderRadius: borderRadius.full,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[5],
    minHeight: 52,
    fontFamily: fonts.regular,
    fontSize: fontSize.base,
    color: colors.textPrimary,
  },
  inputDisabled: {
    backgroundColor: '#FFFFFF',
    borderRadius: borderRadius.full,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[5],
    minHeight: 52,
    fontFamily: fonts.regular,
    fontSize: fontSize.base,
    color: colors.textMuted,
    opacity: 0.6,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: borderRadius.xl,
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[3],
  },
  menuRowPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  menuIconCircle: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  iconShadow: {
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuLabel: {
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: fontSize.base,
    color: colors.textInverse,
    ...TEXT_SHADOW,
  },
  chevron: {
    ...TEXT_SHADOW,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.error,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
  },
  errorText: {
    fontFamily: fonts.medium,
    fontSize: fontSize.sm,
    color: colors.textInverse,
    marginLeft: spacing[2],
    flex: 1,
  },
  saveWrap: {
    marginTop: spacing[4],
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxClose: {
    position: 'absolute',
    top: spacing[12],
    right: spacing[5],
    zIndex: 10,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxImage: {
    width: '85%',
    aspectRatio: 1,
    borderRadius: borderRadius.xl,
  },
});

export default styles;
